{host, ...}: let
  inherit
    (import ../../../hosts/${host}/variables.nix)
    extraMonitorSettings
    ;

  hostWindowRules = import ./hosts/${host}/windowrules.nix {inherit host;};

  defaultWindowRules = [
    "tag:file-manager, class:^(Thunar|org.gnome.Nautilus|pcmanfm-qt)$"
    "tag:terminal, class:^(com.mitchellh.ghostty|org.wezfurlong.wezterm|Alacritty|kitty|kitty-dropterm)$"
    "tag:browser, class:^(Brave-browser(-beta|-dev|-unstable)?)$"
    "tag:browser, class:^(vivaldi-stable)$"
    "tag:browser, class:^(zen-beta)$"
    "tag:browser, class:^(Firefox|org.mozilla.firefox|Firefox-esr)$"
    "tag:browser, class:^(Google-chrome(-beta|-dev|-unstable)?)$"
    "tag:browser, class:^(Thorium-browser|Cachy-browser)$"
    "tag:projects, class:^(codium|codium-url-handler|VSCodium)$"
    "tag:projects, class:^(VSCode|code-url-handler)$"
    "tag:im, class:^(Discord|WebCord|Vesktop)$"
    "tag:im, class:^(Ferdium)$"
    "tag:im, class:^(WhatsApp-for-linux)$"
    "tag:im, class:^(org.telegram.desktop|io.github.tdesktop_x64.TDesktop)$"
    "tag:im, class:^(teams-for-linux)$"
    "tag:ide, class:^(dev.zed.Zed)$"
    "tag:games, class:^(gamescope)$"
    "tag:games, class:^(steam_app_\\d+)$"
    "tag:gamestore, class:^(Steam)$"
    "tag:gamestore, title:^(Lutris)$"
    "tag:gamestore, class:^(com.heroicgameslauncher.hgl)$"
    "tag:settings, class:^(gnome-disks|wihotspot(-gui)?)$"
    "tag:settings, class:^(Rofi)$"
    "tag:settings, class:^(file-roller|org.gnome.FileRoller)$"
    "tag:settings, class:^(nm-applet|nm-connection-editor|blueman-manager)$"
    "tag:settings, class:^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$"
    "tag:settings, class:^(nwg-look|qt5ct|qt6ct|Yad)$"
    "tag:settings, class:^(xdg-desktop-portal-gtk)$"
    "tag:settings, class:^(.blueman-manager-wrapped)$"
    "tag:settings, class:^(nwg-displays)$"
    "move 72% 7%, title:^(Picture-in-Picture)$"
    "center, class:^(Ferdium)$"
    "float, class:^(Waypaper)$"
    "center, class:^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$"
    "center, class:^(Thunar)$, title:negative:(.*Thunar.*)"
    "center, title:^(Authentication Required)$"
    "idleinhibit fullscreen, class:^(.*)$"
    "idleinhibit fullscreen, title:^(.*)$"
    "idleinhibit fullscreen, fullscreen:1"
    "center, class:^(Moonlight)$"
    "float, class:^(Emulator)$"
    "float, tag:settings*"
    "float, class:^(Ferdium)$"
    "float, title:^(Picture-in-Picture)$"
    "float, class:^(mpv|com.github.rafostar.Clapper)$"
    "float, title:^(Authentication Required)$"
    "float, class:^(codium|codium-url-handler|VSCodium)$, title:negative:(.*codium.*|.*VSCodium.*)"
    "float, class:^(com.heroicgameslauncher.hgl)$, title:negative:(Heroic Games Launcher)"
    "float, class:^(Steam)$, title:negative:^(Steam)$"
    "float, class:^(Thunar)$, title:negative:(.*Thunar.*)"
    "float, initialTitle:(Add Folder to Workspace)"
    "float, initialTitle:(Open Files)"
    "float, initialTitle:(wants to save)"
    "size 70% 60%, initialTitle:(Open Files)"
    "size 70% 60%, initialTitle:(Add Folder to Workspace)"
    "size 70% 70%, tag:settings*"
    "size 60% 70%, class:^(Ferdium)$"
    "opacity 0.9 0.7, tag:browser*"
    "opacity 0.9 0.9, class:^(dev\\.heppen\\.webapps\\..*)"
    "opacity 0.9 0.9, class:^(obsidian)$"
    "opacity 0.9 0.9, class:^(com.github.th_ch.youtube_music)$"
    "opacity 0.9 0.8, tag:projects*"
    "opacity 0.9 0.8, tag:im*"
    "opacity 0.9 0.8, tag:file-manager*"
    "opacity 0.8 0.7, tag:terminal*"
    "opacity 0.8 0.7, tag:ide*"
    "opacity 0.8 0.7, tag:settings*"
    "opacity 0.8 0.7, tag:gamestore*"
    "opacity 0.8 0.7, class:^(gedit|org.gnome.TextEditor|mousepad)$"
    "opacity 0.9 0.8, class:^(seahorse)$"
    "opacity 0.95 0.75, title:^(Picture-in-Picture)$"
    "pin, title:^(Picture-in-Picture)$"
    "keepaspectratio, title:^(Picture-in-Picture)$"
    "blur:0, tag:games*"
    "fullscreen, tag:games*"
  ];
in {
  wayland.windowManager.hyprland = {
    settings.windowrulev2 = defaultWindowRules ++ hostWindowRules.windowrule;
  };
}
