# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: let
  rootID = "a60ce0ee-3248-435c-b217-e94213c92527";
  bootID = "D222-EF51";
  homeID = "c00a3013-1baf-4a62-8aed-13d0697bb4c5";
in {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = ["xhci_pci" "nvme" "usbhid" "sdhci_pci"];
      kernelModules = [];
    };
    extraModulePackages = [];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/${rootID}";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/${bootID}";
      fsType = "vfat";
    };

    "/home" = {
      device = "/dev/disk/by-uuid/${homeID}";
      fsType = "ext4";
    };
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
