# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = ["xhci_pci" "nvme" "usbhid" "sdhci_pci"];
      kernelModules = [];
    };
    extraModulePackages = [];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/f3e6826b-1fc9-4e09-a186-22ad36a3ff07";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/F28D-757A";
      fsType = "vfat";
    };

    "/home" = {
      device = "/dev/disk/by-uuid/c00a3013-1baf-4a62-8aed-13d0697bb4c5";
      fsType = "ext4";
    };
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
